name: chatbot-server

services:
  chatbot-server:
    image: ghcr.io/torvian-eu/chatbot-server:latest
    container_name: chatbot-server
    restart: unless-stopped
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      SERVER_CONNECTOR_TYPE: "HTTP"
      SERVER_CORS_ALLOWED_ORIGIN_1: "https://chatbot-client.yourdomain.com" # Change to the actual URL of your chatbot client
    #      JAVA_TOOL_OPTIONS: "-Dlog4j.configurationFile=/app/config/log4j2-debug.xml"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    expose:
      - "8080"
    networks:
      chatbot-network:
        aliases:
          - chatbot-server

networks:
  chatbot-network:
    external: true