services:
  chatbot-server:
    image: ghcr.io/torvian-eu/chatbot-server:latest
    container_name: chatbot-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      SERVER_HOST: "0.0.0.0"
    #      SERVER_PORT: "8080"
      SSL_PORT: "8443"
      SERVER_CONNECTOR_TYPE: "HTTPS"
    #      SERVER_CORS_ALLOWED_ORIGIN_1: "https://192.168.1.50"
    volumes:
      - chatbot-config:/app/config
      - chatbot-data:/app/data
      - chatbot-logs:/app/logs

volumes:
  chatbot-config:
  chatbot-data:
  chatbot-logs: