package eu.torvian.chatbot.common.models.agent

/**
 * Centralized constants for the well-known agent-instruction kind keys.
 *
 * The `instructions` list on [AgentInstructionDto] (via [eu.torvian.chatbot.common.models.agent.AgentRoleDto])
 * is a flat list identified by each entry's `type` field. Kind-specific extra fields (e.g.
 * `modelId` for `model_specific`) are carried in the `custom` JSON object of each entry.
 *
 * This mirrors the constants-object pattern used by `CommonUserGroups` and `CommonPermissions` so that
 * instruction-type strings stay typo-free and centralized across the shared API surface.
 */
object AgentInstructionTypes {

    /**
     * Static role description, e.g. "You are a senior software architect...".
     */
    const val ROLE: String = "role"

    /**
     * Project context, usually `AGENTS.md` content.
     */
    const val MAIN: String = "main"

    /**
     * User-editable free text.
     */
    const val CUSTOM: String = "custom"

    /**
     * Dynamic guidance describing the roles that the current role may spawn.
     *
     * The message is generated by the server from current role metadata; any client-supplied message
     * for this marker is ignored.
     */
    const val SPAWNABLE_AGENTS: String = "spawnable_agents"

    /**
     * Per-model instruction marker: applies only when the conversation is running on the model
     * referenced by `custom.modelId`. Multiple `model_specific` entries are allowed as long as each
     * targets a distinct model.
     */
    const val MODEL_SPECIFIC: String = "model_specific"

    /**
     * Every well-known instruction kind, in canonical display order.
     *
     * Used by server built-in tools and the catalog schemas to enumerate the accepted `type` values
     * (e.g. for validation error messages and JSON-Schema `enum` arrays) without repeating the
     * constants at each call site.
     */
    val allKnown: List<String> = listOf(
        ROLE,
        MAIN,
        CUSTOM,
        SPAWNABLE_AGENTS,
        MODEL_SPECIFIC
    )
}
