package eu.torvian.chatbot.server.service.core.chat.compaction

import eu.torvian.chatbot.common.models.api.core.CompactionCompletedPayload
import kotlin.time.Instant

/**
 * Server-only domain records for persisted conversation-compaction chunks.
 *
 * These records intentionally live outside the common transcript DTOs and outside any provider-facing
 * model: chunk coverage refers to original `ChatMessage` IDs and observed timestamps, which must never
 * be exposed through `RawChatMessage` serialization. A chunk is an immutable full-thread summary with
 * ordered per-message coverage, plus provenance and token-count audit metadata.
 */

/**
 * One ordered source-message coverage entry of a compaction chunk.
 *
 * [ordinal] is the 0-based chronological position of the covered source unit within the summarized
 * thread; [messageId] identifies the original `ChatMessage`; [observedUpdatedAt] is the `updatedAt`
 * timestamp observed when the chunk was created, carried as an [Instant] and persisted as epoch
 * milliseconds only at the DAO boundary. A chunk is eligible for a context only when every recorded
 * pair still matches the current parent chain.
 *
 * @property ordinal Chronological position of the covered source unit within the summarized thread.
 * @property messageId Original message ID covered by the chunk (no FK; see the V26 migration).
 * @property observedUpdatedAt `updatedAt` observed for [messageId] at creation.
 */
data class CompactedMessageCoverage(
    val ordinal: Int,
    val messageId: Long,
    val observedUpdatedAt: Instant
)

/**
 * A persisted, immutable conversation-compaction chunk.
 *
 * @property id Chunk primary key.
 * @property sessionId Owning chat session.
 * @property summary The full-thread summary text generated by the auxiliary compaction model.
 * @property modelId Compaction model ID at creation, or null after the model row was deleted.
 * @property settingsId Compaction settings ID at creation, or null after the settings row was deleted.
 * @property providerId Compaction provider ID at creation, or null after the provider row was deleted.
 * @property modelName Immutable model-name snapshot surviving model deletion.
 * @property settingsName Immutable settings-name snapshot surviving settings deletion.
 * @property providerName Immutable provider-name snapshot surviving provider deletion.
 * @property instruction Exact compaction-instruction snapshot used for this chunk.
 * @property thresholdTokens Threshold that was in effect when this chunk was created.
 * @property sourceTokenCount Estimated full primary input before this compaction.
 * @property resultTokenCount Estimated one-summary primary input after this compaction.
 * @property tokenCounterVersion Version of the repository-owned counter used for the persisted counts.
 * @property coverageCount Number of ordered coverage entries ([coverage] must match this size).
 * @property createdAt Epoch-millisecond creation time.
 * @property coverage Ordered per-message coverage, sorted by [CompactedMessageCoverage.ordinal].
 */
data class ConversationCompactionChunk(
    val id: Long,
    val sessionId: Long,
    val summary: String,
    val modelId: Long?,
    val settingsId: Long?,
    val providerId: Long?,
    val modelName: String,
    val settingsName: String,
    val providerName: String,
    val instruction: String,
    val thresholdTokens: Long,
    val sourceTokenCount: Long,
    val resultTokenCount: Long,
    val tokenCounterVersion: String,
    val coverageCount: Int,
    val createdAt: Long,
    val coverage: List<CompactedMessageCoverage>
)

/**
 * Converts a persisted chunk into the shared, provider-neutral wire notification payload.
 *
 * The summary is reduced to a bounded preview ([CompactionCompletedPayload.MAX_SUMMARY_PREVIEW_CHARS]
 * characters plus a truncation marker) so the event never carries the full summary; the compaction
 * instruction, reasoning content, and credentials are deliberately not included. Coverage is reduced
 * to the ordered original message ids, and provenance is exposed as both the nullable ids and the
 * immutable name snapshots.
 *
 * @receiver The persisted chunk to expose on the event surfaces.
 * @return The bounded wire payload for the `conversation_compacted` event.
 */
fun ConversationCompactionChunk.toCompactionCompletedPayload(): CompactionCompletedPayload {
    val preview = if (summary.length > CompactionCompletedPayload.MAX_SUMMARY_PREVIEW_CHARS) {
        summary.take(CompactionCompletedPayload.MAX_SUMMARY_PREVIEW_CHARS) +
            CompactionCompletedPayload.SUMMARY_PREVIEW_TRUNCATION_MARKER
    } else {
        summary
    }
    return CompactionCompletedPayload(
        chunkId = id,
        sessionId = sessionId,
        coveredMessageIds = coverage.map { covered -> covered.messageId },
        modelId = modelId,
        settingsId = settingsId,
        providerId = providerId,
        modelName = modelName,
        settingsName = settingsName,
        providerName = providerName,
        sourceTokenCount = sourceTokenCount,
        resultTokenCount = resultTokenCount,
        summaryPreview = preview,
        createdAt = createdAt
    )
}

/**
 * A not-yet-persisted compaction chunk awaiting verified atomic insertion.
 *
 * The DAO transaction re-verifies the source chain (session membership, exact timestamps, ordered
 * parent links, final leaf) against [coverage] before inserting the chunk and its coverage rows.
 *
 * @property sessionId Owning chat session.
 * @property summary The full-thread summary text generated by the auxiliary compaction model.
 * @property modelId Compaction model ID (nullable FK, SET NULL on delete).
 * @property settingsId Compaction settings ID (nullable FK, SET NULL on delete).
 * @property providerId Compaction provider ID (nullable FK, SET NULL on delete).
 * @property modelName Immutable model-name snapshot.
 * @property settingsName Immutable settings-name snapshot.
 * @property providerName Immutable provider-name snapshot.
 * @property instruction Exact compaction-instruction snapshot used for this chunk.
 * @property thresholdTokens Threshold that was in effect when this chunk was created.
 * @property sourceTokenCount Estimated full primary input before this compaction.
 * @property resultTokenCount Estimated one-summary primary input after this compaction.
 * @property tokenCounterVersion Version of the repository-owned counter used for the persisted counts.
 * @property createdAt Epoch-millisecond creation time.
 * @property coverage Ordered per-message coverage (ordinals 0..n-1 matching the summarized thread).
 */
data class ConversationCompactionChunkCandidate(
    val sessionId: Long,
    val summary: String,
    val modelId: Long?,
    val settingsId: Long?,
    val providerId: Long?,
    val modelName: String,
    val settingsName: String,
    val providerName: String,
    val instruction: String,
    val thresholdTokens: Long,
    val sourceTokenCount: Long,
    val resultTokenCount: Long,
    val tokenCounterVersion: String,
    val createdAt: Long,
    val coverage: List<CompactedMessageCoverage>
) {
    /** Number of ordered coverage entries this candidate carries. */
    val coverageCount: Int
        get() = coverage.size
}
