package eu.torvian.chatbot.common.models.api.agent

import eu.torvian.chatbot.common.models.agent.AgentInstructionDto
import eu.torvian.chatbot.common.models.agent.AgentInstructionTypes
import kotlinx.serialization.Serializable

/**
 * Request body for creating a new user-defined agent role.
 *
 * A role's LLM configuration is supplied through [modelPresetId], which references a user-owned
 * [eu.torvian.chatbot.common.models.llm.ModelPresetDto] (the model preset is the sole source of truth
 * for the role's model and settings profile). The preset is **optional** at creation time: a role may
 * be created without one and completed later via [UpdateAgentRoleRequest] (e.g. by the server built-in
 * `update_agent_role` tool). A preset-less role — or a role whose preset has a null model/settings
 * reference — is **non-sendable** until repaired; turn preparation raises a model-configuration error
 * for it.
 *
 * @property name Unique (per user) machine-readable role name, non-blank and at most 255 characters.
 * @property displayName Optional human-friendly display name.
 * @property description Free-form description of the role.
 * @property modelPresetId Optional identifier of the model preset that holds the role's model and
 *            settings profile; null means the role has no model configuration and is non-sendable
 *            until a preset is attached. The preset must be owned by the requesting user; a preset
 *            whose model/settings reference is null (the state produced when a referenced row is
 *            deleted) may still be attached — the role simply cannot drive a turn until it is
 *            repaired.
 * @property toolIds Set of tool-definition identifiers to attach to the role. Duplicates are
 *            impossible at the wire level (a set), so no service-side de-duplication is needed.
 * @property spawnableAgentRoleIds Same-user role identifiers that this role may spawn. Duplicates are
 *            impossible at the wire level (a set); self-referencing identifiers are allowed. Every
 *            target must belong to the same project scope as the role ([projectId]): the server
 *            rejects a target bound to a different project or a project-less role targeting an
 *            in-project role (and vice versa).
 * @property instructions Flat instruction list. Instructions of any kind (including
 *            [AgentInstructionTypes.SPAWNABLE_AGENTS],
 *            whose message is generated by the server on every read) are carried through as-is.
 * @property projectId Identifier of the single user-owned project to associate the role with, or
 *            `null` to create an **unassociated** role. The id (when non-null) must reference a
 *            project owned by the requesting user; a missing or foreign id is rejected as not-found
 *            by the server. The default keeps payloads produced before this property existed decoding
 *            as unassociated.
 */
@Serializable
data class CreateAgentRoleRequest(
    val name: String,
    val displayName: String? = null,
    val description: String = "",
    val modelPresetId: Long? = null,
    val toolIds: Set<Long> = emptySet(),
    val spawnableAgentRoleIds: Set<Long> = emptySet(),
    val instructions: List<AgentInstructionDto> = emptyList(),
    val projectId: Long? = null
)
