package eu.torvian.chatbot.common.models.api.agent

import eu.torvian.chatbot.common.models.agent.AgentInstructionDto
import eu.torvian.chatbot.common.models.agent.AgentInstructionTypes
import kotlinx.serialization.Serializable

/**
 * Request body for creating a new user-defined agent role.
 *
 * `modelId`/`modelSettingsId` are optional at creation time: a role may be created without a model
 * and settings and completed later via [UpdateAgentRoleRequest] (e.g. by the server built-in
 * `update_agent_role` tool). A role without a model/settings is **non-sendable** until repaired —
 * turn preparation raises a model-configuration error for it. The persisted columns are nullable
 * anyway (they also become null via `ON DELETE SET NULL` when a referenced model/settings is
 * deleted).
 *
 * @property name Unique (per user) machine-readable role name, non-blank and at most 255 characters.
 * @property displayName Optional human-friendly display name.
 * @property description Free-form description of the role.
 * @property modelId Optional identifier of the LLM model the role uses; null means the role has no
 *            model and is non-sendable until set via update.
 * @property modelSettingsId Optional identifier of the settings profile (CHAT or RESPONSES) the role
 *            uses; null means the role has no settings and is non-sendable until set via update.
 *            When both are provided, the settings must belong to [modelId] and be chat-capable.
 * @property toolIds Set of tool-definition identifiers to attach to the role. Duplicates are
 *            impossible at the wire level (a set), so no service-side de-duplication is needed.
 * @property spawnableAgentRoleIds Same-user role identifiers that this role may spawn. Duplicates are
 *            impossible at the wire level (a set); self-referencing identifiers are allowed.
 * @property instructions Flat instruction list. Instructions of any kind (including
 *            [AgentInstructionTypes.SPAWNABLE_AGENTS],
 *            whose message is generated by the server on every read) are carried through as-is.
 */
@Serializable
data class CreateAgentRoleRequest(
    val name: String,
    val displayName: String? = null,
    val description: String = "",
    val modelId: Long? = null,
    val modelSettingsId: Long? = null,
    val toolIds: Set<Long> = emptySet(),
    val spawnableAgentRoleIds: Set<Long> = emptySet(),
    val instructions: List<AgentInstructionDto> = emptyList()
)
