package eu.torvian.chatbot.common.models.api.agent

import eu.torvian.chatbot.common.models.agent.AgentInstructionDto
import eu.torvian.chatbot.common.models.agent.AgentInstructionTypes
import kotlinx.serialization.Serializable

/**
 * Request body for creating a new user-defined agent role.
 *
 * All fields are present and required at creation time: a role without a model and settings is
 * useless, so `modelId`/`modelSettingsId` are mandatory here even though the persisted columns are
 * nullable (they become null only via `ON DELETE SET NULL` when a referenced model/settings is deleted).
 *
 * @property name Unique (per user) machine-readable role name, non-blank and at most 255 characters.
 * @property displayName Optional human-friendly display name.
 * @property description Free-form description of the role.
 * @property modelId Identifier of the LLM model the role uses.
 * @property modelSettingsId Identifier of the settings profile (CHAT or RESPONSES) the role uses; it
 *            must belong to [modelId] and be chat-capable.
 * @property toolIds Set of tool-definition identifiers to attach to the role. Duplicates are
 *            impossible at the wire level (a set), so no service-side de-duplication is needed.
 * @property spawnableAgentRoleIds Same-user role identifiers that this role may spawn. Duplicates are
 *            impossible at the wire level (a set); self-referencing identifiers are allowed.
 * @property instructions Flat instruction list. Instructions of any kind (including
 *            [AgentInstructionTypes.SPAWNABLE_AGENTS],
 *            whose message is generated by the server on every read) are carried through as-is.
 */
@Serializable
data class CreateAgentRoleRequest(
    val name: String,
    val displayName: String? = null,
    val description: String = "",
    val modelId: Long,
    val modelSettingsId: Long,
    val toolIds: Set<Long> = emptySet(),
    val spawnableAgentRoleIds: Set<Long> = emptySet(),
    val instructions: List<AgentInstructionDto> = emptyList()
)
