package eu.torvian.chatbot.server.service.security

import eu.torvian.chatbot.server.data.dao.ApiSecretDao
import eu.torvian.chatbot.server.data.models.ApiSecretEntity
import eu.torvian.chatbot.server.domain.security.EncryptedSecret
import io.mockk.*
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import java.util.*
import kotlin.test.*

/**
 * Unit tests for [DbEncryptedCredentialManager].
 *
 * This test suite verifies the core orchestration logic of the database-backed credential manager,
 * ensuring it correctly interacts with its dependencies: [EncryptionService] and [ApiSecretDao].
 *
 * Both dependencies are mocked using MockK, focusing on testing the logic *within* the manager
 * and how it responds to success/failure from its collaborators, rather than testing the
 * dependencies themselves.
 */
class DbEncryptedCredentialManagerTest {

    private lateinit var apiSecretDao: ApiSecretDao // The mocked DAO
    private lateinit var encryptionService: EncryptionService // The mocked service
    private lateinit var credentialManager: CredentialManager // The class under test

    // --- Test Data ---
    private val testPlainCredential = "my_super_secret_api_key"
    private val testAlias = "test-alias-123" // A specific alias for lookup/delete tests
    private val testKeyVersion = 1

    private val testEncryptedData = EncryptedSecret(
        encryptedSecret = "encrypted_credential_data",
        encryptedDEK = "wrapped_data_encryption_key",
        keyVersion = testKeyVersion
    )

    // Entity structure we expect the manager to save/retrieve
    // Note: createdAt/updatedAt will be dynamically generated by the manager,
    // so we won't assert exact timestamps, but will capture and check structure.
    private fun expectedApiSecretEntity(alias: String, encryptedSecret: EncryptedSecret): ApiSecretEntity {
        // Return a template entity structure without exact timestamps
        return ApiSecretEntity(
            alias = alias,
            encryptedCredential = encryptedSecret.encryptedSecret,
            wrappedDek = encryptedSecret.encryptedDEK,
            keyVersion = encryptedSecret.keyVersion,
            // Timestamps will be set by the manager under test
            createdAt = 0L, // Placeholder
            updatedAt = 0L  // Placeholder
        )
    }


    @BeforeEach
    fun setUp() {
        // Mock both dependencies
        apiSecretDao = mockk()
        encryptionService = mockk()

        // Create the class under test with mocked dependencies
        credentialManager = DbEncryptedCredentialManager(encryptionService, apiSecretDao)

        // Configure mock responses that are common across tests if needed
        // (None strictly needed for this specific setup, mocks default to null/0/false)
    }

    @AfterEach
    fun tearDown() {
        // Clear all mocks after each test to ensure isolation
        clearMocks(apiSecretDao, encryptionService)
    }

    // --- storeCredential Tests ---

    @Test
    fun `storeCredential should encrypt and save credential successfully`() = runTest {
        // Arrange
        // Configure the mock encryption service to return specific encrypted data
        every { encryptionService.encrypt(testPlainCredential) } returns testEncryptedData

        // Configure the mock apiSecretDao to succeed (return Unit for a Unit function or true for Boolean)
        // apiSecretDao.saveSecret returns Unit
        coEvery { apiSecretDao.saveSecret(any()) } returns Unit // Mock successful save

        // Use a slot to capture the ApiSecretEntity passed to apiSecretDao.saveSecret
        val apiSecretEntitySlot = slot<ApiSecretEntity>()

        // Act
        val resultAlias = credentialManager.storeCredential(testPlainCredential)

        // Assert
        assertNotNull(resultAlias, "storeCredential should return a non-null alias on success")
        // Verify the alias is a valid UUID string (optional but good sanity check)
        assertDoesNotThrow { UUID.fromString(resultAlias) }

        // Verify encryptionService was called correctly
        verify(exactly = 1) { encryptionService.encrypt(testPlainCredential) }

        // Verify apiSecretDao.saveSecret was called exactly once with the captured entity
        coVerify(exactly = 1) { apiSecretDao.saveSecret(capture(apiSecretEntitySlot)) }

        val savedEntity = apiSecretEntitySlot.captured

        // Assert the contents of the saved entity structure
        assertEquals(resultAlias, savedEntity.alias, "Saved entity alias should match the returned alias")
        assertEquals(
            testEncryptedData.encryptedSecret,
            savedEntity.encryptedCredential,
            "Saved entity encrypted credential mismatch"
        )
        assertEquals(testEncryptedData.encryptedDEK, savedEntity.wrappedDek, "Saved entity wrapped DEK mismatch")
        assertEquals(testEncryptedData.keyVersion, savedEntity.keyVersion, "Saved entity key version mismatch")
        // Check timestamps are present and equal (since it's an initial save)
        assertTrue(savedEntity.createdAt > 0, "Saved entity createdAt should be set")
        assertTrue(savedEntity.updatedAt > 0, "Saved entity updatedAt should be set")
        assertEquals(
            savedEntity.createdAt,
            savedEntity.updatedAt,
            "createdAt and updatedAt should be the same on initial save"
        )
    }

    @Test
    fun `storeCredential should return null if encryption fails`() = runTest {
        // Arrange
        // Configure the mock encryption service to throw an exception
        val encryptionException = RuntimeException("Encryption failed!")
        every { encryptionService.encrypt(testPlainCredential) } throws encryptionException

        // Act
        val resultAlias = credentialManager.storeCredential(testPlainCredential)

        // Assert
        assertNull(resultAlias, "storeCredential should return null if encryption fails")

        // Verify encryptionService was called
        verify(exactly = 1) { encryptionService.encrypt(testPlainCredential) }
        // Verify apiSecretDao.saveSecret was NOT called
        coVerify(exactly = 0) { apiSecretDao.saveSecret(any()) }
    }

    @Test
    fun `storeCredential should return null if saving to database fails`() = runTest {
        // Arrange
        // Configure encryption service to succeed
        every { encryptionService.encrypt(testPlainCredential) } returns testEncryptedData
        // Configure apiSecretDao to throw an exception when saveSecret is called
        val dbSaveException = RuntimeException("DB Save failed!")
        coEvery { apiSecretDao.saveSecret(any()) } throws dbSaveException

        // Act
        val resultAlias = credentialManager.storeCredential(testPlainCredential)

        // Assert
        assertNull(resultAlias, "storeCredential should return null if saving to DB fails")

        // Verify encryptionService was called
        verify(exactly = 1) { encryptionService.encrypt(testPlainCredential) }
        // Verify apiSecretDao.saveSecret was called and threw
        coVerify(exactly = 1) { apiSecretDao.saveSecret(any()) }
    }

    // --- getCredential Tests ---

    @Test
    fun `getCredential should retrieve and decrypt credential successfully`() = runTest {
        // Arrange
        // Create a sample entity that we will mock the DAO to return
        val retrievedEntity = expectedApiSecretEntity(testAlias, testEncryptedData).copy(
            createdAt = System.currentTimeMillis(), // Add realistic timestamps for retrieval mock
            updatedAt = System.currentTimeMillis()
        )

        // Configure the mock apiSecretDao to return the entity for the test alias
        coEvery { apiSecretDao.findSecret(testAlias) } returns retrievedEntity

        // Configure the mock encryption service to return the plaintext when decrypting the specific encrypted data
        every { encryptionService.decrypt(testEncryptedData) } returns testPlainCredential

        // Act
        val resultCredential = credentialManager.getCredential(testAlias)

        // Assert
        assertNotNull(resultCredential, "getCredential should return a non-null credential on success")
        assertEquals(testPlainCredential, resultCredential, "Retrieved credential should match the original plaintext")

        // Verify apiSecretDao.findSecret was called correctly
        coVerify(exactly = 1) { apiSecretDao.findSecret(testAlias) }
        // Verify encryptionService.decrypt was called correctly
        verify(exactly = 1) { encryptionService.decrypt(testEncryptedData) }
    }

    @Test
    fun `getCredential should return null if alias is not found in database`() = runTest {
        // Arrange
        val nonExistentAlias = "non-existent-alias"
        // Configure the mock apiSecretDao to return null for a non-existent alias
        coEvery { apiSecretDao.findSecret(nonExistentAlias) } returns null

        // Act
        val resultCredential = credentialManager.getCredential(nonExistentAlias)

        // Assert
        assertNull(resultCredential, "getCredential should return null if alias is not found")

        // Verify apiSecretDao.findSecret was called correctly
        coVerify(exactly = 1) { apiSecretDao.findSecret(nonExistentAlias) }
        // Verify encryptionService.decrypt was NOT called
        verify(exactly = 0) { encryptionService.decrypt(any()) }
    }

    @Test
    fun `getCredential should return null if retrieving from database fails`() = runTest {
        // Arrange
        // Configure apiSecretDao to throw an exception when findSecret is called
        val dbFindException = RuntimeException("DB Find failed!")
        coEvery { apiSecretDao.findSecret(testAlias) } throws dbFindException

        // Act
        val resultCredential = credentialManager.getCredential(testAlias)

        // Assert
        assertNull(resultCredential, "getCredential should return null if retrieving from DB fails")

        // Verify apiSecretDao.findSecret was called and threw
        coVerify(exactly = 1) { apiSecretDao.findSecret(testAlias) }
        // Verify encryptionService.decrypt was NOT called
        verify(exactly = 0) { encryptionService.decrypt(any()) }
    }

    @Test
    fun `getCredential should return null if decryption fails`() = runTest {
        // Arrange
        // Create a sample entity that we will mock the DAO to return
        val retrievedEntity = expectedApiSecretEntity(testAlias, testEncryptedData).copy(
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )
        // Configure the mock apiSecretDao to return the entity
        coEvery { apiSecretDao.findSecret(testAlias) } returns retrievedEntity

        // Configure the mock encryption service to throw an exception when decrypting
        val decryptionException = RuntimeException("Decryption failed!")
        every { encryptionService.decrypt(testEncryptedData) } throws decryptionException

        // Act
        val resultCredential = credentialManager.getCredential(testAlias)

        // Assert
        assertNull(resultCredential, "getCredential should return null if decryption fails")

        // Verify apiSecretDao.findSecret was called
        coVerify(exactly = 1) { apiSecretDao.findSecret(testAlias) }
        // Verify encryptionService.decrypt was called and threw
        verify(exactly = 1) { encryptionService.decrypt(testEncryptedData) }
    }


    // --- deleteCredential Tests ---

    @Test
    fun `deleteCredential should delete credential successfully when found`() = runTest {
        // Arrange
        // Configure apiSecretDao to return true for deletion success (as per DAO contract logic)
        coEvery { apiSecretDao.deleteSecret(testAlias) } returns true

        // Act
        val isDeleted = credentialManager.deleteCredential(testAlias)

        // Assert
        assertTrue(isDeleted, "deleteCredential should return true on successful deletion")

        // Verify apiSecretDao.deleteSecret was called correctly
        coVerify(exactly = 1) { apiSecretDao.deleteSecret(testAlias) }

        // Verify encryptionService was not called (delete doesn't involve encryption/decryption)
        verify { encryptionService wasNot Called }
    }

    @Test
    fun `deleteCredential should return true if alias is not found (already deleted state)`() = runTest {
        // Arrange
        val nonExistentAlias = "non-existent-alias"
        // Configure apiSecretDao to return true for deletion of a non-existent alias
        // (This matches the common DAO pattern where delete returns true if the item is not there or successfully removed)
        coEvery { apiSecretDao.deleteSecret(nonExistentAlias) } returns true

        // Act
        val isDeleted = credentialManager.deleteCredential(nonExistentAlias)

        // Assert
        assertTrue(isDeleted, "deleteCredential should return true even if the alias is not found")

        // Verify apiSecretDao.deleteSecret was called
        coVerify(exactly = 1) { apiSecretDao.deleteSecret(nonExistentAlias) }

        // Verify encryptionService was not called
        verify { encryptionService wasNot Called }
    }

    @Test
    fun `deleteCredential should return false if deleting from database fails (DAO returns false)`() = runTest {
        // Arrange
        // Configure apiSecretDao to return false, indicating a DB failure *handled by the DAO*
        coEvery { apiSecretDao.deleteSecret(testAlias) } returns false

        // Act
        val isDeleted = credentialManager.deleteCredential(testAlias)

        // Assert
        assertFalse(isDeleted, "deleteCredential should return false if the database deletion fails")

        // Verify apiSecretDao.deleteSecret was called
        coVerify(exactly = 1) { apiSecretDao.deleteSecret(testAlias) }

        // Verify encryptionService was not called
        verify { encryptionService wasNot Called }
    }

    @Test
    fun `deleteCredential should return false if database operation throws exception`() = runTest {
        // Arrange
        // Configure apiSecretDao to throw an exception during deletion
        val dbDeleteException = RuntimeException("DB Delete failed unexpectedly!")
        coEvery { apiSecretDao.deleteSecret(testAlias) } throws dbDeleteException

        // Act
        val isDeleted = credentialManager.deleteCredential(testAlias)

        // Assert
        assertFalse(isDeleted, "deleteCredential should return false if the database operation throws an exception")

        // Verify apiSecretDao.deleteSecret was called
        coVerify(exactly = 1) { apiSecretDao.deleteSecret(testAlias) }

        // Verify encryptionService was not called
        verify { encryptionService wasNot Called }
    }
}