package eu.torvian.chatbot.server.data.tables

import org.jetbrains.exposed.v1.core.ReferenceOption
import org.jetbrains.exposed.v1.core.dao.id.LongIdTable

/**
 * Exposed table definition for persisted conversation-compaction chunks.
 *
 * Each row is one immutable full-thread summary produced when an enabled primary LLM input exceeded
 * the user's configured threshold. Rows are retained forever; eligibility and newest-overlap
 * selection are computed against the selected parent chain, never by mutating or deleting rows.
 *
 * @property sessionId Owning chat session; deleting the session cascades away all of its chunks.
 * @property summary The full-thread summary text generated by the auxiliary compaction model.
 * @property modelId Nullable FK to the compaction model (SET NULL on delete).
 * @property settingsId Nullable FK to the compaction settings profile (SET NULL on delete).
 * @property providerId Nullable FK to the compaction provider (SET NULL on delete).
 * @property modelName Immutable model-name snapshot surviving model deletion.
 * @property settingsName Immutable settings-name snapshot surviving settings deletion.
 * @property providerName Immutable provider-name snapshot surviving provider deletion.
 * @property instruction Exact compaction-instruction snapshot used for this chunk (provenance/reproducibility).
 * @property thresholdTokens Threshold that was in effect when this chunk was created.
 * @property sourceTokenCount Estimated full primary input before this compaction.
 * @property resultTokenCount Estimated one-summary primary input after this compaction.
 * @property tokenCounterVersion Version of the repository-owned counter used for the persisted counts.
 * @property coverageCount Number of ordered coverage rows stored for this chunk.
 * @property createdAt Epoch-millisecond creation time; combined with [id] for deterministic newest ordering.
 */
object ConversationCompactionChunkTable : LongIdTable("conversation_compaction_chunks") {
    val sessionId = reference("session_id", ChatSessionTable, onDelete = ReferenceOption.CASCADE)
    val summary = text("summary")
    val modelId = reference("model_id", LLMModelTable, onDelete = ReferenceOption.SET_NULL).nullable()
    val settingsId = reference("settings_id", ModelSettingsTable, onDelete = ReferenceOption.SET_NULL).nullable()
    val providerId = reference("provider_id", LLMProviderTable, onDelete = ReferenceOption.SET_NULL).nullable()
    val modelName = varchar("model_name", 255)
    val settingsName = varchar("settings_name", 255)
    val providerName = varchar("provider_name", 255)
    val instruction = text("instruction")
    val thresholdTokens = long("threshold_tokens")
    val sourceTokenCount = long("source_token_count")
    val resultTokenCount = long("result_token_count")
    val tokenCounterVersion = varchar("token_counter_version", 50)
    val coverageCount = integer("coverage_count")
    val createdAt = long("created_at")

    init {
        // Mirrors the migration index; Exposed cannot express DESC sort orders in `index`, but the
        // leading (session_id, created_at) columns still serve the per-session newest-first scan.
        index(false, sessionId, createdAt, id)
    }
}
