package eu.torvian.chatbot.server.data.dao

import eu.torvian.chatbot.common.models.core.AssistantMessageErrorCode
import eu.torvian.chatbot.common.models.core.AssistantMessageIncompleteCause

/**
 * Write-side completion state of an assistant message row (`assistant_messages`).
 *
 * This is the write contract of [MessageDao.insertMessage] / [MessageDao.updateMessageContent]: it groups the
 * four persisted columns so a caller can only ever write a documented, internally consistent combination.
 *
 * Invariants (generated by the factories in the companion object, not enforced by the constructor):
 * - [Completed]: `isComplete = true` and no cause, code or message.
 * - [InFlight]: `isComplete = false` with no cause yet — the message is still being generated (streaming
 *   placeholder) and the UI renders nothing for it.
 * - [InterruptedByUser]: `isComplete = false` with cause `INTERRUPTED_BY_USER` and no code/message, because the
 *   client localizes the interruption label from the cause.
 * - [failed]: `isComplete = false` with cause `FAILED`, a machine-readable code and a non-null bounded reason.
 *
 * A data class is used (rather than an enum or sealed type) because the values are compared by argument
 * matchers in tests; always build values through the factories so the invariants hold.
 *
 * @property isComplete Whether the message completed normally.
 * @property incompleteCause Terminal incompletion cause, or `null` when no terminal cause is known.
 * @property errorCode Machine-readable failure classification, only set for a failure.
 * @property errorMessage Bounded, provider-internal-free failure reason, only set for a failure.
 */
data class AssistantMessageCompletionState(
    val isComplete: Boolean,
    val incompleteCause: AssistantMessageIncompleteCause? = null,
    val errorCode: AssistantMessageErrorCode? = null,
    val errorMessage: String? = null
) {
    companion object {
        /**
         * Upper bound, in characters, of [errorMessage] as persisted. Mirrors the bounded-text precedent used by
         * other shared payloads (`CompactionCompletedPayload.MAX_SUMMARY_PREVIEW_CHARS`) so a message column can
         * never grow with provider output.
         */
        const val MAX_ERROR_MESSAGE_CHARS: Int = 500

        /**
         * Marker appended when an error message is shortened to [MAX_ERROR_MESSAGE_CHARS]. The marker is part of
         * the persisted text and therefore counts toward the character budget.
         */
        const val ERROR_MESSAGE_TRUNCATION_MARKER: String = "…"

        /** A message that completed normally: no cause, code or reason is recorded. */
        val Completed: AssistantMessageCompletionState = AssistantMessageCompletionState(isComplete = true)

        /**
         * A message whose generation is still running: it is not completed, but no terminal cause exists yet.
         * Clients deliberately render nothing for this combination.
         */
        val InFlight: AssistantMessageCompletionState = AssistantMessageCompletionState(isComplete = false)

        /**
         * A message the user stopped before it completed. No code or reason is recorded: the interruption label
         * is localized by the client from the cause alone.
         */
        val InterruptedByUser: AssistantMessageCompletionState = AssistantMessageCompletionState(
            isComplete = false,
            incompleteCause = AssistantMessageIncompleteCause.INTERRUPTED_BY_USER
        )

        /**
         * A failed message carrying its machine-readable code and bounded, user-facing reason.
         *
         * The reason is the only place technical failures are allowed to become text; it must never be built from
         * provider response bodies or exception messages, and it is truncated here so no caller can persist an
         * unbounded string.
         *
         * @param code Machine-readable classification of the failure.
         * @param message User-facing, provider-internal-free reason; shortened to [MAX_ERROR_MESSAGE_CHARS]
         *        with [ERROR_MESSAGE_TRUNCATION_MARKER] when it exceeds that budget.
         * @return A failure state with cause `FAILED`, the given code, and the (possibly truncated) reason.
         */
        fun failed(code: AssistantMessageErrorCode, message: String): AssistantMessageCompletionState =
            AssistantMessageCompletionState(
                isComplete = false,
                incompleteCause = AssistantMessageIncompleteCause.FAILED,
                errorCode = code,
                errorMessage = message.boundToErrorMessageBudget()
            )

        /**
         * Shortens [this] to [MAX_ERROR_MESSAGE_CHARS] characters, appending
         * [ERROR_MESSAGE_TRUNCATION_MARKER] so the truncation stays visible in the UI. Texts that already fit
         * are returned unchanged, and the marker is always counted toward the budget.
         *
         * @receiver The candidate error message.
         * @return The bounded message, never longer than [MAX_ERROR_MESSAGE_CHARS].
         */
        private fun String.boundToErrorMessageBudget(): String =
            if (length <= MAX_ERROR_MESSAGE_CHARS) this
            else take(MAX_ERROR_MESSAGE_CHARS - ERROR_MESSAGE_TRUNCATION_MARKER.length) +
                ERROR_MESSAGE_TRUNCATION_MARKER
    }
}
